#!/usr/bin/perl
# 93dc4303ce5535e5b288fb27c7b17187
# uwe@schimon.de 20220103
$_=$string="uwe.schimon@mailpost.de 04 06 07 10 11 12 13 14 15 16 17 20 22 23 1212 20220103";

($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime((stat $0)[8]);
($Y, $M, $D) = split(/ /,sprintf("%04d %02d %02d", $year+1900, $mon+1, $mday));

@f= split(/ /);
foreach (@f) {
 if(/[^\d]/) {
  $author= $_
 } else {
  $time= $_;
  if(/^(\d\d\d\d)(\d\d)(\d\d)$/) {
   $Y=$1; $M=$2; $D=$3;
  } elsif(/^(\d\d)(\d\d)$/) {
   $M=$1; $D= $2;
  } elsif(/^(\d\d)$/) {
   $D=$1;
  }
  $time="$Y$M$D";
 }
 print "$author\t$time\n";
 }
